### PR TITLE
data is able to get store in local storage but there is some more issue like not able to filter by month.

### PR DESCRIPTION
**Pull request by adasarpan404**
### Bugs Remaining

- [x] Filter by month 
- [x] CSS code got breaked

### CODE REVIEW

**Review by nidhish-srivastava — COMMENTED** [review]
I am not able to understand your code properly,i get it when u use localstorage.getItem in App.js,
but your NewExpenses code,i m not getting,and data is not being added dynamically,i need to refresh it every timei add,
No problem though,thanks for even trying

**Comment by adasarpan404** [comment]
I will also resolve for not refreshing issue because we have to add useeffect to get data.

**Comment by adasarpan404** [comment]
check @nidhish-srivastava

**Comment by nidhish-srivastava** [comment]
> check @nidhish-srivastava

Good,just try solving the month issue,i will merge ur pr,thanks though :))

**Comment by adasarpan404** [comment]
filter by month done

**Review by nidhish-srivastava — COMMENTED** [review]
Good Job brother and thanks a lot for solving this issue

**Comment by nidhish-srivastava** [comment]
> filter by month done

There is one bug,we delete the item,it is removed,but if we reload the page,the item appears again,Solve this

**Comment by adasarpan404** [comment]
ok i will solve this

**Pull request merged**
